version: "3.8"

services:
  database:
    image: xterminatorgrp2xterminator.azurecr.io/xterminatordb:v1
    container_name: mysql-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: xter
      MYSQL_USER: chaymae
      MYSQL_PASSWORD: chay
    restart: always

  server:
    image: xterminatorgrp2xterminator.azurecr.io/xterminatorback:v1
    container_name: fastapi-server
    depends_on:
      - database
    ports:
      - "3310:3310"
    restart: always

  client:
    image: xterminatorgrp2xterminator.azurecr.io/xterminator:v1
    container_name: react-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

volumes:
  database_data:
    driver: local
