services:

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: mysql-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: xter
      MYSQL_USER: chaymae
      MYSQL_PASSWORD: chay
    restart: always

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: fastapi-server
    depends_on:
      - database
    ports:
      - "3310:3310"
    restart: always

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

volumes:
  database_data:
    driver: local
