from .message_route import router as message_router
from .register_route import router as register_router
from .tag_route import router as tag_router
from .login_route import router as login_router
from .user_route import router as user_router
from .token_route import router as token_router
from .adminStats_route import router as admin_router
from .reaction_route import router as reaction_router
from .reactiontype_route import router as reactiontype_router
from .adminreactions_route import router as adminreactions_router
